export const REQUEST_POIS = "REQUEST_POIS";
export const RECEIVE_POIS = "RECEIVE_POIS";
export const REQUEST_LOCATION = "REQUEST_LOCATION";
export const ERROR_LOCATION = "ERROR_LOCATION";
export const RECEIVE_LOCATION = "RECEIVE_LOCATION";




